baseURL: "https://vitorfhc.github.io/vitorfalcao.com/"
languageCode: en-us
title: Vitor Falcao
theme: PaperMod

params:
  env: production

  ShowCodeCopyButtons: true

  outputs:
    home:
      - HTML
      - JSON # is necessary

  homeInfoParams:
    enabled: true
    Title: "Bug Bounty Hunter & Security Researcher"
    Content: |
      Brazilian cybersecurity enthusiast sharing real-world hacking techniques, bug bounty strategies, and security research.
      Aka **busfactor**

  profileMode:
    enabled: false
    title: Fixing stuff
    subtitle: I decided to take some time to fix my blog :)

  socialIcons:
    - name: Intigriti
      url: https://app.intigriti.com/profile/egl
    - name: HackerOne
      url: https://hackerone.com/busf4ctor?type=user
    - name: GitHub
      url: https://github.com/vitorfhc
    - name: Twitter
      url: https://twitter.com/busf4ctor
    # - name: Medium
    # url: https://vitorfalcao.medium.com/
    - name: LinkedIn
      url: https://www.linkedin.com/in/vitorfhc/
    - name: Email
      url: mailto:vitorfhcosta@gmail.com

  ShowShareButtons: true
  ShowReadingTime: true
  ShowToc: true
  # UseHugoToc: true

  analytics:
    umami:
      id: d24005e5-dcfe-4705-95a9-af30ca480eff
      script_url: https://cloud.umami.is/script.js
